<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Edit</name>
   <tag></tag>
   <elementGuidId>24cf28b7-6a11-4c47-adb6-082e6148a273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[3]/div[2]/div/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.action.edit > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62e42b07-0230-4925-915b-d0e41a0a6d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>78edcac7-49fc-4601-aa4b-cf82942ccd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;block block-dashboard-info&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;box box-information&quot;]/div[@class=&quot;box-actions&quot;]/a[@class=&quot;action edit&quot;]/span[1]</value>
      <webElementGuid>0f5d5aeb-c7f5-42b8-8c5a-d16bfe11dacd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[3]/div[2]/div/div[2]/a/span</value>
      <webElementGuid>1a3c1711-d624-407e-b293-18736ac6662b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Information'])[1]/following::span[1]</value>
      <webElementGuid>116cbee3-e719-467a-a8a2-b0c496bf78a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/following::span[2]</value>
      <webElementGuid>f537b636-4ea6-4587-86d1-1cb79c8afd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::span[1]</value>
      <webElementGuid>cac5a153-7d77-42ee-92e7-e3c72ddc2315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Book'])[1]/preceding::span[1]</value>
      <webElementGuid>80adc399-f1b7-454f-9b8c-2a87d1e5b2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>e8605684-450c-4cdc-a4b8-29f4d88fd6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>3c720acd-5428-4426-af08-6c7eef41d9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>59b3af82-cc2e-41b1-a0f7-1f164be40f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
